name: Deploy Servlet App

on:
  push:
    branches: [development, dev, check_branch,java_check-1]
  pull_request:
    branches: [development, dev, check_branch]
jobs:
   deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Copy WAR file to IIS directory
      run: |
        # Copy the WAR file to the directory where IIS is configured for Java Servlet applications

    - name: Restart IIS
      run: |
        # Restart IIS to apply changes
