name: Run unit tests
 
on:
  push:
    branches: [ development , dev ]
  pull_request:
    branches: [ development , dev ]
 
jobs:  
  test:
    runs-on: ubuntu-latest
 
    steps:
    - name : Checkout code
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        echo ${GITHUB_WORKSPACE}
        sudo mkdir -p ~/.ssh/
        echo ${GITHUB_WORKSPACE}
        cd ~
        ls -al
        sudo chmod 777 ~/.ssh/
        echo "${{ secrets.PUB_KEY }}" > ~/.ssh/id_rsa.pub
        sudo sh -c 'echo "${{ secrets.PVT_KEY}}" > ~/.ssh/id_rsa'
        sudo sh -c 'chmod -f 600 ~/.ssh/id_rsa ~/.ssh/id_rsa.pub'
        sudo sh -c 'ssh-keyscan github.com >> ~/.ssh/known_hosts'
        sudo sh -c 'chmod -f 644 ~/.ssh/known_hosts'
        cd ~
        ls -al
        cd .ssh
        ls -al
        sudo sh -c 'eval `ssh-agent -s` '
        sudo sh -c 'ssh-agent -a /tmp/ssh_agent.sock > /dev/null'
        echo "added agent"
        sudo -E sh -c 'ssh-add < echo "${{ secrets.PVT_KEY}}" '
        git clone git@github.com:Akamardeep/poc.git
 
    - name : Install Packages
      run : pip install coverage
 
    - name: unit test
      run: |
        ls -al
        chmod +x ${{ github.workspace }}/test.py
        python ${{ github.workspace }}/test.py
        coverage report -m --fail-under=80
