name: Run unit tests

on:
  push:
    branches: [development, dev, check_branch]
  pull_request:
    branches: [development, dev, check_branch]

jobs:
  build:
    name: Build Angular Project
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
         ls
         pwd

      - name: Install Angular CLI
        run: npm install -g @angular/cli
