name: Run unit tests
 
on:
  push:
    branches: [ development , dev ]
  pull_request:
    branches: [ development , dev ]
 
jobs:  
  test:
    runs-on: ubuntu-latest
 
    steps:
    - name : Checkout code
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        echo ${GITHUB_WORKSPACE}
        sudo mkdir -p ~/.ssh/
        echo ${GITHUB_WORKSPACE}
        cd ~
        ls -al
        sudo chmod 777 ~/.ssh/
        echo "${{ secrets.PUB_KEY }}" > ~/.ssh/id_rsa.pub
        echo "${{ secrets.PVT_KEY}}" > ~/.ssh/id_rsa
        chmod -f 600 ~/.ssh/id_rsa ~/.ssh/id_rsa.pub
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        chmod -f 644 ~/.ssh/known_hosts
        cd ~
        ls -al
        cd .ssh
        ls -al
        eval $(ssh-agent)
        ssh-agent -a /tmp/ssh_agent.sock > /dev/null
        echo "added agent"
        ssh-add ~/.ssh/id_rsa
        git clone git@github.com:Akamardeep/poc.git
        cd poc
        git checkout development
        git pull
        ls -al
        echo ${{ github.workspace }}
 
    - name : Install Packages
      run : pip install coverage
 
    - name: unit test
      run: |
        git clone git@github.com:Akamardeep/poc.git
        cd poc
        git checkout development
        git pull
        ls -al
        echo ${{ github.workspace }}
        ls -al
        chmod +x ./test.py
        python ./test.py
        pip install -r requirements.txt
        coverage report -m --fail-under=80
 
