name: Run unit tests

on:
  push:
    branches:
      - development
      - dev
      - check_branch
      - check_1
      
  pull_request:
    branches:
      - development
      - dev
      - check_branch
      - check_1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          pip install coverage

      - name: Display Branch Name
        run: |
          echo ${GITHUB_EVENT_NAME}
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          elif [[ $GITHUB_EVENT_NAME == 'push' && $GITHUB_REF == refs/heads/* ]]; then
            BRANCH_NAME="${GITHUB_REF/refs\/heads\//}"
          fi
          echo ${BRANCH_NAME}
          
      - name: Set variable
        run: echo "a=fail" >> $GITHUB_ENV

      - name: Check condition and fail if necessary
        if: ${{ env.a == 'fail' }}
        run: exit 1

      - name: Unit Test
        run: |
          ls -al
          chmod +x ${{ github.workspace }}/test.py
          python ${{ github.workspace }}/test.py
          coverage report -m --fail-under=80
