name: Run unit tests

on:
  push:
    branches:
      - development
      - dev
      - check_branch
      - check_1
      
  pull_request:
    branches:
      - development
      - dev
      - check_branch
      - check_1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          pip install coverage

      - name: Display Branch Name
        run: |
          echo ${GITHUB_EVENT_NAME}
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          elif [[ $GITHUB_EVENT_NAME == 'push' && $GITHUB_REF == refs/heads/* ]]; then
            BRANCH_NAME="${GITHUB_REF/refs\/heads\//}"
          fi
          echo ${BRANCH_NAME}
          echo ${GITHUB_WORKSPACE}
          ls -la
          coverage=$(cat ./lcov-report/index.html | grep -A 1 "class='fl pad1y space-right2'" | awk 'NR==2' | sed 's/^[^>]*>//;s/<.*$//')
           echo "coverage=${coverage}" >> $GITHUB_ENV
          echo ${coverage}
          
          echo "test_cov=100" >> $GITHUB_ENV
          echo ${test_cov}
          if [[ ${test_cov} -lt 90 ]]; then
            exit 1
          fi

      - name: Unit Test
        run: |
          ls -al
          chmod +x ${{ github.workspace }}/test.py
          python ${{ github.workspace }}/test.py
          coverage report -m --fail-under=80
